/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PeopleRouteImport } from './routes/people/route'
import { Route as AuthRouteImport } from './routes/auth/route'
import { Route as IndexImport } from './routes/index'
import { Route as TvIndexImport } from './routes/tv/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as TvTvIdImport } from './routes/tv/$tvId'
import { Route as PeoplePersonIdImport } from './routes/people/$personId'
import { Route as MovieMovieIdImport } from './routes/movie/$movieId'
import { Route as AuthVerifyImport } from './routes/auth/verify'
import { Route as AuthSignupImport } from './routes/auth/sign_up'
import { Route as AuthProfileImport } from './routes/auth/profile'
import { Route as PeopleLayoutIndexImport } from './routes/people/_layout.index'
import { Route as MovieListListImport } from './routes/movie/list/$list'
import { Route as MovieTypeTypeNameTypeIdImport } from './routes/movie/$type.$typeName.$typeId'

// Create/Update Routes

const PeopleRouteRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TvIndexRoute = TvIndexImport.update({
  id: '/tv/',
  path: '/tv/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const TvTvIdRoute = TvTvIdImport.update({
  id: '/tv/$tvId',
  path: '/tv/$tvId',
  getParentRoute: () => rootRoute,
} as any)

const PeoplePersonIdRoute = PeoplePersonIdImport.update({
  id: '/$personId',
  path: '/$personId',
  getParentRoute: () => PeopleRouteRoute,
} as any)

const MovieMovieIdRoute = MovieMovieIdImport.update({
  id: '/movie/$movieId',
  path: '/movie/$movieId',
  getParentRoute: () => rootRoute,
} as any)

const AuthVerifyRoute = AuthVerifyImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/sign_up',
  path: '/sign_up',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthProfileRoute = AuthProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRouteRoute,
} as any)

const PeopleLayoutIndexRoute = PeopleLayoutIndexImport.update({
  id: '/_layout/',
  path: '/',
  getParentRoute: () => PeopleRouteRoute,
} as any)

const MovieListListRoute = MovieListListImport.update({
  id: '/movie/list/$list',
  path: '/movie/list/$list',
  getParentRoute: () => rootRoute,
} as any)

const MovieTypeTypeNameTypeIdRoute = MovieTypeTypeNameTypeIdImport.update({
  id: '/movie/$type/$typeName/$typeId',
  path: '/movie/$type/$typeName/$typeId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRoute
    }
    '/auth/profile': {
      id: '/auth/profile'
      path: '/profile'
      fullPath: '/auth/profile'
      preLoaderRoute: typeof AuthProfileImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/sign_up': {
      id: '/auth/sign_up'
      path: '/sign_up'
      fullPath: '/auth/sign_up'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyImport
      parentRoute: typeof AuthRouteImport
    }
    '/movie/$movieId': {
      id: '/movie/$movieId'
      path: '/movie/$movieId'
      fullPath: '/movie/$movieId'
      preLoaderRoute: typeof MovieMovieIdImport
      parentRoute: typeof rootRoute
    }
    '/people/$personId': {
      id: '/people/$personId'
      path: '/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof PeoplePersonIdImport
      parentRoute: typeof PeopleRouteImport
    }
    '/tv/$tvId': {
      id: '/tv/$tvId'
      path: '/tv/$tvId'
      fullPath: '/tv/$tvId'
      preLoaderRoute: typeof TvTvIdImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/tv/': {
      id: '/tv/'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvIndexImport
      parentRoute: typeof rootRoute
    }
    '/movie/list/$list': {
      id: '/movie/list/$list'
      path: '/movie/list/$list'
      fullPath: '/movie/list/$list'
      preLoaderRoute: typeof MovieListListImport
      parentRoute: typeof rootRoute
    }
    '/people/_layout/': {
      id: '/people/_layout/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleLayoutIndexImport
      parentRoute: typeof PeopleRouteImport
    }
    '/movie/$type/$typeName/$typeId': {
      id: '/movie/$type/$typeName/$typeId'
      path: '/movie/$type/$typeName/$typeId'
      fullPath: '/movie/$type/$typeName/$typeId'
      preLoaderRoute: typeof MovieTypeTypeNameTypeIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AuthRouteRouteChildren {
  AuthProfileRoute: typeof AuthProfileRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthProfileRoute: AuthProfileRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PeopleRouteRouteChildren {
  PeoplePersonIdRoute: typeof PeoplePersonIdRoute
  PeopleLayoutIndexRoute: typeof PeopleLayoutIndexRoute
}

const PeopleRouteRouteChildren: PeopleRouteRouteChildren = {
  PeoplePersonIdRoute: PeoplePersonIdRoute,
  PeopleLayoutIndexRoute: PeopleLayoutIndexRoute,
}

const PeopleRouteRouteWithChildren = PeopleRouteRoute._addFileChildren(
  PeopleRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/people': typeof PeopleRouteRouteWithChildren
  '/auth/profile': typeof AuthProfileRoute
  '/auth/sign_up': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/tv/$tvId': typeof TvTvIdRoute
  '/auth/': typeof AuthIndexRoute
  '/tv': typeof TvIndexRoute
  '/movie/list/$list': typeof MovieListListRoute
  '/people/': typeof PeopleLayoutIndexRoute
  '/movie/$type/$typeName/$typeId': typeof MovieTypeTypeNameTypeIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/sign_up': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/tv/$tvId': typeof TvTvIdRoute
  '/auth': typeof AuthIndexRoute
  '/tv': typeof TvIndexRoute
  '/movie/list/$list': typeof MovieListListRoute
  '/people': typeof PeopleLayoutIndexRoute
  '/movie/$type/$typeName/$typeId': typeof MovieTypeTypeNameTypeIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/people': typeof PeopleRouteRouteWithChildren
  '/auth/profile': typeof AuthProfileRoute
  '/auth/sign_up': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/tv/$tvId': typeof TvTvIdRoute
  '/auth/': typeof AuthIndexRoute
  '/tv/': typeof TvIndexRoute
  '/movie/list/$list': typeof MovieListListRoute
  '/people/_layout/': typeof PeopleLayoutIndexRoute
  '/movie/$type/$typeName/$typeId': typeof MovieTypeTypeNameTypeIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/people'
    | '/auth/profile'
    | '/auth/sign_up'
    | '/auth/verify'
    | '/movie/$movieId'
    | '/people/$personId'
    | '/tv/$tvId'
    | '/auth/'
    | '/tv'
    | '/movie/list/$list'
    | '/people/'
    | '/movie/$type/$typeName/$typeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/profile'
    | '/auth/sign_up'
    | '/auth/verify'
    | '/movie/$movieId'
    | '/people/$personId'
    | '/tv/$tvId'
    | '/auth'
    | '/tv'
    | '/movie/list/$list'
    | '/people'
    | '/movie/$type/$typeName/$typeId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/people'
    | '/auth/profile'
    | '/auth/sign_up'
    | '/auth/verify'
    | '/movie/$movieId'
    | '/people/$personId'
    | '/tv/$tvId'
    | '/auth/'
    | '/tv/'
    | '/movie/list/$list'
    | '/people/_layout/'
    | '/movie/$type/$typeName/$typeId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PeopleRouteRoute: typeof PeopleRouteRouteWithChildren
  MovieMovieIdRoute: typeof MovieMovieIdRoute
  TvTvIdRoute: typeof TvTvIdRoute
  TvIndexRoute: typeof TvIndexRoute
  MovieListListRoute: typeof MovieListListRoute
  MovieTypeTypeNameTypeIdRoute: typeof MovieTypeTypeNameTypeIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PeopleRouteRoute: PeopleRouteRouteWithChildren,
  MovieMovieIdRoute: MovieMovieIdRoute,
  TvTvIdRoute: TvTvIdRoute,
  TvIndexRoute: TvIndexRoute,
  MovieListListRoute: MovieListListRoute,
  MovieTypeTypeNameTypeIdRoute: MovieTypeTypeNameTypeIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/people",
        "/movie/$movieId",
        "/tv/$tvId",
        "/tv/",
        "/movie/list/$list",
        "/movie/$type/$typeName/$typeId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth/route.tsx",
      "children": [
        "/auth/profile",
        "/auth/sign_up",
        "/auth/verify",
        "/auth/"
      ]
    },
    "/people": {
      "filePath": "people/route.tsx",
      "children": [
        "/people/$personId",
        "/people/_layout/"
      ]
    },
    "/auth/profile": {
      "filePath": "auth/profile.tsx",
      "parent": "/auth"
    },
    "/auth/sign_up": {
      "filePath": "auth/sign_up.tsx",
      "parent": "/auth"
    },
    "/auth/verify": {
      "filePath": "auth/verify.tsx",
      "parent": "/auth"
    },
    "/movie/$movieId": {
      "filePath": "movie/$movieId.tsx"
    },
    "/people/$personId": {
      "filePath": "people/$personId.tsx",
      "parent": "/people"
    },
    "/tv/$tvId": {
      "filePath": "tv/$tvId.tsx"
    },
    "/auth/": {
      "filePath": "auth/index.tsx",
      "parent": "/auth"
    },
    "/tv/": {
      "filePath": "tv/index.tsx"
    },
    "/movie/list/$list": {
      "filePath": "movie/list/$list.tsx"
    },
    "/people/_layout/": {
      "filePath": "people/_layout.index.tsx",
      "parent": "/people"
    },
    "/movie/$type/$typeName/$typeId": {
      "filePath": "movie/$type.$typeName.$typeId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
