/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TvRouteImport } from './routes/tv/route'
import { Route as PeopleRouteImport } from './routes/people/route'
import { Route as MovieRouteImport } from './routes/movie/route'
import { Route as AuthRouteImport } from './routes/auth/route'
import { Route as IndexImport } from './routes/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as TvTvIdImport } from './routes/tv/$tvId'
import { Route as PeoplePersonIdImport } from './routes/people/$personId'
import { Route as MovieMovieIdImport } from './routes/movie/$movieId'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthResetpasswordImport } from './routes/auth/reset_password'
import { Route as TvLayoutIndexImport } from './routes/tv/_layout.index'
import { Route as PeopleLayoutIndexImport } from './routes/people/_layout.index'
import { Route as TvLayoutTopRatedImport } from './routes/tv/_layout.top-rated'
import { Route as TvLayoutPopularImport } from './routes/tv/_layout.popular'
import { Route as TvLayoutOnTheAirImport } from './routes/tv/_layout.on-the-air'
import { Route as TvLayoutAiringTodayImport } from './routes/tv/_layout.airing-today'
import { Route as MovieLayoutUpcomingImport } from './routes/movie/_layout.upcoming'
import { Route as MovieLayoutTopratedImport } from './routes/movie/_layout.top_rated'
import { Route as MovieLayoutPopularImport } from './routes/movie/_layout.popular'
import { Route as MovieLayoutNowplayingImport } from './routes/movie/_layout.now_playing'
import { Route as MovieTypeTypeNameTypeIdImport } from './routes/movie/$type.$typeName.$typeId'

// Create/Update Routes

const TvRouteRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRoute,
} as any)

const PeopleRouteRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRoute,
} as any)

const MovieRouteRoute = MovieRouteImport.update({
  id: '/movie',
  path: '/movie',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const TvTvIdRoute = TvTvIdImport.update({
  id: '/$tvId',
  path: '/$tvId',
  getParentRoute: () => TvRouteRoute,
} as any)

const PeoplePersonIdRoute = PeoplePersonIdImport.update({
  id: '/$personId',
  path: '/$personId',
  getParentRoute: () => PeopleRouteRoute,
} as any)

const MovieMovieIdRoute = MovieMovieIdImport.update({
  id: '/$movieId',
  path: '/$movieId',
  getParentRoute: () => MovieRouteRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthResetpasswordRoute = AuthResetpasswordImport.update({
  id: '/reset_password',
  path: '/reset_password',
  getParentRoute: () => AuthRouteRoute,
} as any)

const TvLayoutIndexRoute = TvLayoutIndexImport.update({
  id: '/_layout/',
  path: '/',
  getParentRoute: () => TvRouteRoute,
} as any)

const PeopleLayoutIndexRoute = PeopleLayoutIndexImport.update({
  id: '/_layout/',
  path: '/',
  getParentRoute: () => PeopleRouteRoute,
} as any)

const TvLayoutTopRatedRoute = TvLayoutTopRatedImport.update({
  id: '/_layout/top-rated',
  path: '/top-rated',
  getParentRoute: () => TvRouteRoute,
} as any)

const TvLayoutPopularRoute = TvLayoutPopularImport.update({
  id: '/_layout/popular',
  path: '/popular',
  getParentRoute: () => TvRouteRoute,
} as any)

const TvLayoutOnTheAirRoute = TvLayoutOnTheAirImport.update({
  id: '/_layout/on-the-air',
  path: '/on-the-air',
  getParentRoute: () => TvRouteRoute,
} as any)

const TvLayoutAiringTodayRoute = TvLayoutAiringTodayImport.update({
  id: '/_layout/airing-today',
  path: '/airing-today',
  getParentRoute: () => TvRouteRoute,
} as any)

const MovieLayoutUpcomingRoute = MovieLayoutUpcomingImport.update({
  id: '/_layout/upcoming',
  path: '/upcoming',
  getParentRoute: () => MovieRouteRoute,
} as any)

const MovieLayoutTopratedRoute = MovieLayoutTopratedImport.update({
  id: '/_layout/top_rated',
  path: '/top_rated',
  getParentRoute: () => MovieRouteRoute,
} as any)

const MovieLayoutPopularRoute = MovieLayoutPopularImport.update({
  id: '/_layout/popular',
  path: '/popular',
  getParentRoute: () => MovieRouteRoute,
} as any)

const MovieLayoutNowplayingRoute = MovieLayoutNowplayingImport.update({
  id: '/_layout/now_playing',
  path: '/now_playing',
  getParentRoute: () => MovieRouteRoute,
} as any)

const MovieTypeTypeNameTypeIdRoute = MovieTypeTypeNameTypeIdImport.update({
  id: '/$type/$typeName/$typeId',
  path: '/$type/$typeName/$typeId',
  getParentRoute: () => MovieRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/movie': {
      id: '/movie'
      path: '/movie'
      fullPath: '/movie'
      preLoaderRoute: typeof MovieRouteImport
      parentRoute: typeof rootRoute
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRoute
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRoute
    }
    '/auth/reset_password': {
      id: '/auth/reset_password'
      path: '/reset_password'
      fullPath: '/auth/reset_password'
      preLoaderRoute: typeof AuthResetpasswordImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof AuthRouteImport
    }
    '/movie/$movieId': {
      id: '/movie/$movieId'
      path: '/$movieId'
      fullPath: '/movie/$movieId'
      preLoaderRoute: typeof MovieMovieIdImport
      parentRoute: typeof MovieRouteImport
    }
    '/people/$personId': {
      id: '/people/$personId'
      path: '/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof PeoplePersonIdImport
      parentRoute: typeof PeopleRouteImport
    }
    '/tv/$tvId': {
      id: '/tv/$tvId'
      path: '/$tvId'
      fullPath: '/tv/$tvId'
      preLoaderRoute: typeof TvTvIdImport
      parentRoute: typeof TvRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/movie/_layout/now_playing': {
      id: '/movie/_layout/now_playing'
      path: '/now_playing'
      fullPath: '/movie/now_playing'
      preLoaderRoute: typeof MovieLayoutNowplayingImport
      parentRoute: typeof MovieRouteImport
    }
    '/movie/_layout/popular': {
      id: '/movie/_layout/popular'
      path: '/popular'
      fullPath: '/movie/popular'
      preLoaderRoute: typeof MovieLayoutPopularImport
      parentRoute: typeof MovieRouteImport
    }
    '/movie/_layout/top_rated': {
      id: '/movie/_layout/top_rated'
      path: '/top_rated'
      fullPath: '/movie/top_rated'
      preLoaderRoute: typeof MovieLayoutTopratedImport
      parentRoute: typeof MovieRouteImport
    }
    '/movie/_layout/upcoming': {
      id: '/movie/_layout/upcoming'
      path: '/upcoming'
      fullPath: '/movie/upcoming'
      preLoaderRoute: typeof MovieLayoutUpcomingImport
      parentRoute: typeof MovieRouteImport
    }
    '/tv/_layout/airing-today': {
      id: '/tv/_layout/airing-today'
      path: '/airing-today'
      fullPath: '/tv/airing-today'
      preLoaderRoute: typeof TvLayoutAiringTodayImport
      parentRoute: typeof TvRouteImport
    }
    '/tv/_layout/on-the-air': {
      id: '/tv/_layout/on-the-air'
      path: '/on-the-air'
      fullPath: '/tv/on-the-air'
      preLoaderRoute: typeof TvLayoutOnTheAirImport
      parentRoute: typeof TvRouteImport
    }
    '/tv/_layout/popular': {
      id: '/tv/_layout/popular'
      path: '/popular'
      fullPath: '/tv/popular'
      preLoaderRoute: typeof TvLayoutPopularImport
      parentRoute: typeof TvRouteImport
    }
    '/tv/_layout/top-rated': {
      id: '/tv/_layout/top-rated'
      path: '/top-rated'
      fullPath: '/tv/top-rated'
      preLoaderRoute: typeof TvLayoutTopRatedImport
      parentRoute: typeof TvRouteImport
    }
    '/people/_layout/': {
      id: '/people/_layout/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleLayoutIndexImport
      parentRoute: typeof PeopleRouteImport
    }
    '/tv/_layout/': {
      id: '/tv/_layout/'
      path: '/'
      fullPath: '/tv/'
      preLoaderRoute: typeof TvLayoutIndexImport
      parentRoute: typeof TvRouteImport
    }
    '/movie/$type/$typeName/$typeId': {
      id: '/movie/$type/$typeName/$typeId'
      path: '/$type/$typeName/$typeId'
      fullPath: '/movie/$type/$typeName/$typeId'
      preLoaderRoute: typeof MovieTypeTypeNameTypeIdImport
      parentRoute: typeof MovieRouteImport
    }
  }
}

// Create and export the route tree

interface AuthRouteRouteChildren {
  AuthResetpasswordRoute: typeof AuthResetpasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthResetpasswordRoute: AuthResetpasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MovieRouteRouteChildren {
  MovieMovieIdRoute: typeof MovieMovieIdRoute
  MovieLayoutNowplayingRoute: typeof MovieLayoutNowplayingRoute
  MovieLayoutPopularRoute: typeof MovieLayoutPopularRoute
  MovieLayoutTopratedRoute: typeof MovieLayoutTopratedRoute
  MovieLayoutUpcomingRoute: typeof MovieLayoutUpcomingRoute
  MovieTypeTypeNameTypeIdRoute: typeof MovieTypeTypeNameTypeIdRoute
}

const MovieRouteRouteChildren: MovieRouteRouteChildren = {
  MovieMovieIdRoute: MovieMovieIdRoute,
  MovieLayoutNowplayingRoute: MovieLayoutNowplayingRoute,
  MovieLayoutPopularRoute: MovieLayoutPopularRoute,
  MovieLayoutTopratedRoute: MovieLayoutTopratedRoute,
  MovieLayoutUpcomingRoute: MovieLayoutUpcomingRoute,
  MovieTypeTypeNameTypeIdRoute: MovieTypeTypeNameTypeIdRoute,
}

const MovieRouteRouteWithChildren = MovieRouteRoute._addFileChildren(
  MovieRouteRouteChildren,
)

interface PeopleRouteRouteChildren {
  PeoplePersonIdRoute: typeof PeoplePersonIdRoute
  PeopleLayoutIndexRoute: typeof PeopleLayoutIndexRoute
}

const PeopleRouteRouteChildren: PeopleRouteRouteChildren = {
  PeoplePersonIdRoute: PeoplePersonIdRoute,
  PeopleLayoutIndexRoute: PeopleLayoutIndexRoute,
}

const PeopleRouteRouteWithChildren = PeopleRouteRoute._addFileChildren(
  PeopleRouteRouteChildren,
)

interface TvRouteRouteChildren {
  TvTvIdRoute: typeof TvTvIdRoute
  TvLayoutAiringTodayRoute: typeof TvLayoutAiringTodayRoute
  TvLayoutOnTheAirRoute: typeof TvLayoutOnTheAirRoute
  TvLayoutPopularRoute: typeof TvLayoutPopularRoute
  TvLayoutTopRatedRoute: typeof TvLayoutTopRatedRoute
  TvLayoutIndexRoute: typeof TvLayoutIndexRoute
}

const TvRouteRouteChildren: TvRouteRouteChildren = {
  TvTvIdRoute: TvTvIdRoute,
  TvLayoutAiringTodayRoute: TvLayoutAiringTodayRoute,
  TvLayoutOnTheAirRoute: TvLayoutOnTheAirRoute,
  TvLayoutPopularRoute: TvLayoutPopularRoute,
  TvLayoutTopRatedRoute: TvLayoutTopRatedRoute,
  TvLayoutIndexRoute: TvLayoutIndexRoute,
}

const TvRouteRouteWithChildren =
  TvRouteRoute._addFileChildren(TvRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/movie': typeof MovieRouteRouteWithChildren
  '/people': typeof PeopleRouteRouteWithChildren
  '/tv': typeof TvRouteRouteWithChildren
  '/auth/reset_password': typeof AuthResetpasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/tv/$tvId': typeof TvTvIdRoute
  '/auth/': typeof AuthIndexRoute
  '/movie/now_playing': typeof MovieLayoutNowplayingRoute
  '/movie/popular': typeof MovieLayoutPopularRoute
  '/movie/top_rated': typeof MovieLayoutTopratedRoute
  '/movie/upcoming': typeof MovieLayoutUpcomingRoute
  '/tv/airing-today': typeof TvLayoutAiringTodayRoute
  '/tv/on-the-air': typeof TvLayoutOnTheAirRoute
  '/tv/popular': typeof TvLayoutPopularRoute
  '/tv/top-rated': typeof TvLayoutTopRatedRoute
  '/people/': typeof PeopleLayoutIndexRoute
  '/tv/': typeof TvLayoutIndexRoute
  '/movie/$type/$typeName/$typeId': typeof MovieTypeTypeNameTypeIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movie': typeof MovieRouteRouteWithChildren
  '/auth/reset_password': typeof AuthResetpasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/tv/$tvId': typeof TvTvIdRoute
  '/auth': typeof AuthIndexRoute
  '/movie/now_playing': typeof MovieLayoutNowplayingRoute
  '/movie/popular': typeof MovieLayoutPopularRoute
  '/movie/top_rated': typeof MovieLayoutTopratedRoute
  '/movie/upcoming': typeof MovieLayoutUpcomingRoute
  '/tv/airing-today': typeof TvLayoutAiringTodayRoute
  '/tv/on-the-air': typeof TvLayoutOnTheAirRoute
  '/tv/popular': typeof TvLayoutPopularRoute
  '/tv/top-rated': typeof TvLayoutTopRatedRoute
  '/people': typeof PeopleLayoutIndexRoute
  '/tv': typeof TvLayoutIndexRoute
  '/movie/$type/$typeName/$typeId': typeof MovieTypeTypeNameTypeIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/movie': typeof MovieRouteRouteWithChildren
  '/people': typeof PeopleRouteRouteWithChildren
  '/tv': typeof TvRouteRouteWithChildren
  '/auth/reset_password': typeof AuthResetpasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/tv/$tvId': typeof TvTvIdRoute
  '/auth/': typeof AuthIndexRoute
  '/movie/_layout/now_playing': typeof MovieLayoutNowplayingRoute
  '/movie/_layout/popular': typeof MovieLayoutPopularRoute
  '/movie/_layout/top_rated': typeof MovieLayoutTopratedRoute
  '/movie/_layout/upcoming': typeof MovieLayoutUpcomingRoute
  '/tv/_layout/airing-today': typeof TvLayoutAiringTodayRoute
  '/tv/_layout/on-the-air': typeof TvLayoutOnTheAirRoute
  '/tv/_layout/popular': typeof TvLayoutPopularRoute
  '/tv/_layout/top-rated': typeof TvLayoutTopRatedRoute
  '/people/_layout/': typeof PeopleLayoutIndexRoute
  '/tv/_layout/': typeof TvLayoutIndexRoute
  '/movie/$type/$typeName/$typeId': typeof MovieTypeTypeNameTypeIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/movie'
    | '/people'
    | '/tv'
    | '/auth/reset_password'
    | '/auth/signup'
    | '/movie/$movieId'
    | '/people/$personId'
    | '/tv/$tvId'
    | '/auth/'
    | '/movie/now_playing'
    | '/movie/popular'
    | '/movie/top_rated'
    | '/movie/upcoming'
    | '/tv/airing-today'
    | '/tv/on-the-air'
    | '/tv/popular'
    | '/tv/top-rated'
    | '/people/'
    | '/tv/'
    | '/movie/$type/$typeName/$typeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/movie'
    | '/auth/reset_password'
    | '/auth/signup'
    | '/movie/$movieId'
    | '/people/$personId'
    | '/tv/$tvId'
    | '/auth'
    | '/movie/now_playing'
    | '/movie/popular'
    | '/movie/top_rated'
    | '/movie/upcoming'
    | '/tv/airing-today'
    | '/tv/on-the-air'
    | '/tv/popular'
    | '/tv/top-rated'
    | '/people'
    | '/tv'
    | '/movie/$type/$typeName/$typeId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/movie'
    | '/people'
    | '/tv'
    | '/auth/reset_password'
    | '/auth/signup'
    | '/movie/$movieId'
    | '/people/$personId'
    | '/tv/$tvId'
    | '/auth/'
    | '/movie/_layout/now_playing'
    | '/movie/_layout/popular'
    | '/movie/_layout/top_rated'
    | '/movie/_layout/upcoming'
    | '/tv/_layout/airing-today'
    | '/tv/_layout/on-the-air'
    | '/tv/_layout/popular'
    | '/tv/_layout/top-rated'
    | '/people/_layout/'
    | '/tv/_layout/'
    | '/movie/$type/$typeName/$typeId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MovieRouteRoute: typeof MovieRouteRouteWithChildren
  PeopleRouteRoute: typeof PeopleRouteRouteWithChildren
  TvRouteRoute: typeof TvRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MovieRouteRoute: MovieRouteRouteWithChildren,
  PeopleRouteRoute: PeopleRouteRouteWithChildren,
  TvRouteRoute: TvRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/movie",
        "/people",
        "/tv"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth/route.tsx",
      "children": [
        "/auth/reset_password",
        "/auth/signup",
        "/auth/"
      ]
    },
    "/movie": {
      "filePath": "movie/route.tsx",
      "children": [
        "/movie/$movieId",
        "/movie/_layout/now_playing",
        "/movie/_layout/popular",
        "/movie/_layout/top_rated",
        "/movie/_layout/upcoming",
        "/movie/$type/$typeName/$typeId"
      ]
    },
    "/people": {
      "filePath": "people/route.tsx",
      "children": [
        "/people/$personId",
        "/people/_layout/"
      ]
    },
    "/tv": {
      "filePath": "tv/route.tsx",
      "children": [
        "/tv/$tvId",
        "/tv/_layout/airing-today",
        "/tv/_layout/on-the-air",
        "/tv/_layout/popular",
        "/tv/_layout/top-rated",
        "/tv/_layout/"
      ]
    },
    "/auth/reset_password": {
      "filePath": "auth/reset_password.tsx",
      "parent": "/auth"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx",
      "parent": "/auth"
    },
    "/movie/$movieId": {
      "filePath": "movie/$movieId.tsx",
      "parent": "/movie"
    },
    "/people/$personId": {
      "filePath": "people/$personId.tsx",
      "parent": "/people"
    },
    "/tv/$tvId": {
      "filePath": "tv/$tvId.tsx",
      "parent": "/tv"
    },
    "/auth/": {
      "filePath": "auth/index.tsx",
      "parent": "/auth"
    },
    "/movie/_layout/now_playing": {
      "filePath": "movie/_layout.now_playing.tsx",
      "parent": "/movie"
    },
    "/movie/_layout/popular": {
      "filePath": "movie/_layout.popular.tsx",
      "parent": "/movie"
    },
    "/movie/_layout/top_rated": {
      "filePath": "movie/_layout.top_rated.tsx",
      "parent": "/movie"
    },
    "/movie/_layout/upcoming": {
      "filePath": "movie/_layout.upcoming.tsx",
      "parent": "/movie"
    },
    "/tv/_layout/airing-today": {
      "filePath": "tv/_layout.airing-today.tsx",
      "parent": "/tv"
    },
    "/tv/_layout/on-the-air": {
      "filePath": "tv/_layout.on-the-air.tsx",
      "parent": "/tv"
    },
    "/tv/_layout/popular": {
      "filePath": "tv/_layout.popular.tsx",
      "parent": "/tv"
    },
    "/tv/_layout/top-rated": {
      "filePath": "tv/_layout.top-rated.tsx",
      "parent": "/tv"
    },
    "/people/_layout/": {
      "filePath": "people/_layout.index.tsx",
      "parent": "/people"
    },
    "/tv/_layout/": {
      "filePath": "tv/_layout.index.tsx",
      "parent": "/tv"
    },
    "/movie/$type/$typeName/$typeId": {
      "filePath": "movie/$type.$typeName.$typeId.tsx",
      "parent": "/movie"
    }
  }
}
ROUTE_MANIFEST_END */
